#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""jarvis-agent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Qwen (Speech-to-Text)
- Qwen (LLM)
- Qwen (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.turn.smart_turn.local_smart_turn_v3 import LocalSmartTurnAnalyzerV3
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import LLMRunFrame, TranscriptionMessage, TranscriptionUpdateFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.processors.frameworks.rtvi import RTVIObserver, RTVIProcessor, RTVIClientMessage
from pipecat.processors.transcript_processor import TranscriptProcessor
from pipecat.services.mcp_service import MCPClient
from mcp.client.session_group import StreamableHttpParameters
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.websocket.fastapi import FastAPIWebsocketTransport, FastAPIWebsocketParams, FastAPIWebsocketClient
from pipecat.serializers.protobuf import ProtobufFrameSerializer
from pipecat_tail.observer import TailObserver
from pipecat_whisker import WhiskerObserver

from jarvis.qwen.asr import QwenASRService
from jarvis.qwen.tts import QwenTTSService
from pipecat.adapters.schemas.function_schema import FunctionSchema
from pipecat.adapters.schemas.tools_schema import ToolsSchema
from jarvis.llm.image_analyzer import ImageAnalyzer
from jarvis.serializer import JSONFrameSerializer

load_dotenv(override=True)


def load_system_prompt() -> str:
    """Load system prompt from system_prompt.md file.
    
    Returns:
        The system prompt content, or a default prompt if the file doesn't exist or can't be read.
    """
    default_prompt = "你是一个AI助手，主要通过语音来与用户沟通，不要生成表情、Markdown语法符号等内容，保证你输出的内容符合口语风格"
    prompt_file = os.path.join(os.path.dirname(__file__), "system_prompt.md")
    
    try:
        with open(prompt_file, "r", encoding="utf-8") as f:
            content = f.read().strip()
            # Remove markdown headers if present (lines starting with #)
            lines = [line for line in content.split("\n") if not line.strip().startswith("#")]
            return "\n".join(lines).strip() or default_prompt
    except FileNotFoundError:
        logger.warning(f"System prompt file not found: {prompt_file}. Using default prompt.")
        return default_prompt
    except Exception as e:
        logger.error(f"Error reading system prompt file: {e}. Using default prompt.")
        return default_prompt


async def run_bot(websocket_client: FastAPIWebsocketClient):
    transport = FastAPIWebsocketTransport(
        websocket=websocket_client,
        params=FastAPIWebsocketParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
            add_wav_header=False,
            vad_analyzer=SileroVADAnalyzer(),
            turn_analyzer=LocalSmartTurnAnalyzerV3(),
            serializer=JSONFrameSerializer(),
        )
    )

    """Main bot logic."""
    logger.info("Starting bot")

    # Text-to-Speech service
    tts = QwenTTSService(
        api_key=os.getenv("QWEN_API_KEY"),
        # voice=os.getenv("QWEN_TTS_VOICE", "Cherry"),
        model=os.getenv("QWEN_TTS_MODEL", "qwen3-tts-flash-realtime"),
        # language=os.getenv("QWEN_TTS_LANGUAGE", "auto")
    )

    asr = QwenASRService(
        api_key=os.getenv('QWEN_API_KEY'),
        model='paraformer-realtime-v2'
        # record_base='recordings'
    )

    # LLM service
    llm = OpenAILLMService(
        base_url=os.getenv("OPENAI_BASE_URL"),
        model=os.getenv("OPENAI_LLM_MODEL"),
        api_key=os.getenv("OPENAI_API_KEY")
    )

    ha_mcp = MCPClient(
        server_params=StreamableHttpParameters(
            url=f'{os.getenv('HOMEASSISTANT_BASE_URL')}/api/mcp',
            headers={
                'Authorization': f'Bearer {os.getenv('HOMEASSISTANT_API_KEY')}'
            }
        )
    )
    ha_tools = await ha_mcp.register_tools(llm)

    websearch = MCPClient(
        server_params=StreamableHttpParameters(
            url='https://open.bigmodel.cn/api/mcp/web_search_prime/mcp',
            headers={
                'Authorization': f'Bearer {os.getenv('GLM_API_KEY')}'
            }
        )
    )
    websearch_tools = await websearch.register_tools(llm)

    image_analyzer = ImageAnalyzer(
        base_url=os.getenv("OPENAI_BASE_URL"),
        api_key=os.getenv('GLM_API_KEY'),
        model='glm-4.6v'
    )

    # Load system prompt from file
    system_prompt = load_system_prompt()
    logger.info(f"Loaded system prompt: {system_prompt[:50]}...")
    
    messages = [
        {
            "role": "system",
            "content": system_prompt,
        },
    ]

    all_tools = ToolsSchema(
        standard_tools=[
            *ha_tools.standard_tools,
            *websearch_tools.standard_tools,
            FunctionSchema(
                name='CloseWhenNothingToDo',
                description='Call this function when you have nothing to do and want to say goodbye',
                properties={},
                required=[],
            ),
            FunctionSchema(
                name='SetBrightness',
                description='Set brightness of the glasses. If user said change brightness, it means change brightness of the glasses, you should call this function.',
                properties={
                    'value': {
                        'type': 'integer',
                        'min': 1,
                        'max': 15
                    }
                },
                required=['value']
            ),
            FunctionSchema(
                name='TakePhoto',
                description='在用户的视角拍一张照片。',
                properties={},
                required=[],
            ),
            FunctionSchema(
                name='AnalyzeImage',
                description='Analyze image content. image_uuid is the uuid result you use TakePhoto to generate before, prompts is what you want to analyze with this photo. A photo can only be analyzed for 1 times.',
                properties={
                    'image_uuid': {
                        'type': 'string',
                    },
                    'prompts': {
                        'type': 'string',
                    },
                },
                required=['image_uuid', 'prompts']
            )
        ],
    )

    context = LLMContext(
        messages,
        all_tools,
    )
    context_aggregator = LLMContextAggregatorPair(context)

    # Transcription processor
    transcript_processor = TranscriptProcessor()

    rtvi = RTVIProcessor()

    llm.register_function('AnalyzeImage', image_analyzer.handle_function_call)
    llm.register_function(None, rtvi.handle_function_call)

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            rtvi,
            asr,
            transcript_processor.user(),
            context_aggregator.user(),
            llm,
            tts,
            transport.output(),
            transcript_processor.assistant(),
            context_aggregator.assistant(),
        ]
    )

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
            RTVIObserver(rtvi),
            WhiskerObserver(pipeline),
            TailObserver(),
        ],
        cancel_on_idle_timeout=False,
        idle_timeout_secs=None,
    )

    @rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi: RTVIProcessor):
        await rtvi.set_bot_ready()

    @rtvi.event_handler("on_client_message")
    async def on_client_message(_, msg: RTVIClientMessage):
        match msg.type:
            case 'pic-result':
                image_analyzer.push_image(msg.data['uuid'], msg.data['data'])
                logger.info('Got pic-result, saved to cache')
            case _:
                logger.info(f'Received unknown type of client message: {msg.type}')

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    @transcript_processor.event_handler("on_transcript_update")
    async def on_transcript_update(processor: TranscriptProcessor, frame: TranscriptionUpdateFrame):
        for msg in frame.messages:
            if isinstance(msg, TranscriptionMessage):
                timestamp = f"[{msg.timestamp}] " if msg.timestamp else ""
                line = f"{timestamp}{msg.role}: {msg.content}"
                logger.info(f"Transcript: {line}")

    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)
