#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""jarvis-agent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Qwen (Speech-to-Text)
- Qwen (LLM)
- Qwen (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.turn.smart_turn.local_smart_turn_v3 import LocalSmartTurnAnalyzerV3
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import LLMRunFrame, TranscriptionMessage, TranscriptionUpdateFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.processors.frameworks.rtvi import RTVIObserver, RTVIProcessor
from pipecat.processors.transcript_processor import TranscriptProcessor
from pipecat.runner.types import RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.services.mcp_service import MCPClient
from mcp.client.session_group import StreamableHttpParameters
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat_tail.observer import TailObserver
from pipecat_whisker import WhiskerObserver

from qwen.asr import QwenASRService
from qwen.tts import QwenTTSService
from jarvis.client import ClientSideTools, RegisterClientSideToolsFrame
from pipecat.adapters.schemas.function_schema import FunctionSchema

load_dotenv(override=True)


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Text-to-Speech service
    tts = QwenTTSService(
        api_key=os.getenv("QWEN_API_KEY"),
        # voice=os.getenv("QWEN_TTS_VOICE", "Cherry"),
        model=os.getenv("QWEN_TTS_MODEL", "qwen3-tts-flash-realtime"),
        # language=os.getenv("QWEN_TTS_LANGUAGE", "auto")
    )

    asr = QwenASRService(
        api_key=os.getenv('QWEN_API_KEY'),
        model='paraformer-realtime-v2'
        # record_base='recordings'
    )

    # LLM service
    llm = OpenAILLMService(
        base_url=os.getenv("OPENAI_BASE_URL"),
        model=os.getenv("OPENAI_LLM_MODEL"),
        api_key=os.getenv("OPENAI_API_KEY")
    )

    mcp = MCPClient(
        server_params=StreamableHttpParameters(
            url=f'{os.getenv('HOMEASSISTANT_BASE_URL')}/api/mcp',
            headers={
                'Authorization': f'Bearer {os.getenv('HOMEASSISTANT_API_KEY')}'
            }
        )
    )
    tools = await mcp.register_tools(llm)

    client_side_tools = ClientSideTools()

    messages = [
        {
            "role": "system",
            "content": "You are a friendly AI assistant. Respond naturally and keep your answers conversational.",
        },
        {
            "role": "user",
            "content": "你好"
        }
    ]

    context = LLMContext(
        messages,
        tools,
    )
    context_aggregator = LLMContextAggregatorPair(context)

    # Transcription processor
    transcript_processor = TranscriptProcessor()

    rtvi = RTVIProcessor()

    llm.register_function(None, rtvi.handle_function_call)

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            rtvi,
            client_side_tools,
            asr,
            transcript_processor.user(),
            context_aggregator.user(),
            llm,
            tts,
            transport.output(),
            transcript_processor.assistant(),
            context_aggregator.assistant(),
        ]
    )

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
            RTVIObserver(rtvi),
            WhiskerObserver(pipeline),
            TailObserver(),
        ],
    )

    @rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi: RTVIProcessor):
        tools.standard_tools.append(FunctionSchema(
            name='CloseWhenNothingToDo',
            description='Call this function when you have nothing to do and want to say goodbye',
            properties={},
            required=[],
        ))
        await rtvi.set_bot_ready()
        await task.queue_frame(RegisterClientSideToolsFrame())
        # Kick off the conversation
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    @transcript_processor.event_handler("on_transcript_update")
    async def on_transcript_update(processor: TranscriptProcessor, frame: TranscriptionUpdateFrame):
        for msg in frame.messages:
            if isinstance(msg, TranscriptionMessage):
                timestamp = f"[{msg.timestamp}] " if msg.timestamp else ""
                line = f"{timestamp}{msg.role}: {msg.content}"
                logger.info(f"Transcript: {line}")

    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                    audio_in_channels=1,
                    audio_in_sample_rate=16000,
                    vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.2)),
                    turn_analyzer=LocalSmartTurnAnalyzerV3(),
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
