pipeline {
    agent {
        label 'kaniko'
    }
    
    environment {
        DOCKER_IMAGE = 'docker.zcar.tech/jarvis/server'
        DOCKER_TAG = 'latest'
    }
    
    stages {
        stage('Build and Push Docker Image') {
            when {
                changeset "server/**"
            }
            steps {
                container('kaniko') {
                    script {
                        sh """
                        /kaniko/executor \
                            --dockerfile=Dockerfile \
                            --context=dir://workspace/server \
                            --destination=${DOCKER_IMAGE}:${DOCKER_TAG} \
                            --cache=true \
                            --cache-dir=/cache \
                            --verbosity=info
                        """
                    }
                }
            }
        }
    }
    
    post {
        success {
            echo "Docker image ${DOCKER_IMAGE}:${DOCKER_TAG} built and pushed successfully!"
        }
        failure {
            echo "Failed to build and push Docker image!"
        }
    }
}